version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongoTest
    ports:
    - "27018:27017"
    networks:
      - netApi
    restart: always

  api-test:
    build: .
    container_name: api-python
    depends_on:
      - mongodb
    hostname: api-test
    restart: always
    ports:
      - "5001:5000"
    networks:
      - netApi

networks:
  netApi:
    driver: bridge
